var cards = [
    {title:'Object Store',
  updated: '2 days ago',
  category:'objectStore',
  cluster: 'all',
  entities: 1,
  state:'available',
  clusterAffected:0,
  },

  {title:'LCM',
  updated: '2 days ago',
  category:'lcm',
  cluster: 'all',
  entities: 1,
  state:'available',
  clusterAffected:0,
  },
  {title:'Prism Central',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'all',
  entities: 1,
  state:'In Progress',
  clusterAffected:0,
  },
  {title:'Prism Central',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'all',
  entities: 1,
  state:'available',
  clusterAffected:10,
  },
  {title:'Software component',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 10,
  state:'In Progress',
  clusterAffected:3,
  },

  {title:'Hypervisor',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 30,
  state:'In Progress',
  clusterAffected:3,
  },

  {title:'Acropolis OS',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 10,
  state:'In Progress',
  clusterAffected:2,
  },

  {title:'Host Boot Devices',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 30,
  state:'In Progress',
  clusterAffected:1,
  },

  {title:'NICs',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 120,
  state:'In Progress',
  clusterAffected:3,
  },

  {title:'HBA',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 30,
  state:'In Progress',
  clusterAffected:4,
  },

  {title:'BMC',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 30,
  state:'In Progress',
  clusterAffected:2,
  },

  {title:'SATA Drives',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 60,
  state:'In Progress',
  clusterAffected:2,
  },

  {title:'HDD Firmware',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 60,
  state:'In Progress',
  clusterAffected:2,
  },

  {title:'File Server',
  updated: '2 days ago',
  category:'ahv',
  cluster: 'clustername',
  entities: 60,
  state:'In Progress',
  clusterAffected:1,
  },
];



var buttons = [
  {title: 'Update All',
  class : 'primary-alt',
  secondClass : 'multi-primary',
  arrow: true
},

  {title: 'Schedule',
  class : 'secondary-alt',
  secondClass : 'schedule-popup',
  arrow: false
},

  {title: 'Options',
  class : 'secondary-alt',
  secondClass : 'options-popup',
  arrow: false
  }
];
